# https://github.com/marketplace/actions/github-action-for-firebase
name: Production Firebase Deployment & Lighthouse Audit
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"
          extended: true
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: hugo --minify --baseURL="https://www.nfrost.dev"
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: public
          path: public
          retention-days: 1
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --message \"${{ github.event.head_commit.message }}\"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v3
        with:
          configPath: "./.github/lighthouse/config.json"
          budgetPath: "./.github/lighthouse/budget.json"
          temporaryPublicStorage: true
          urls: |
            https://www.nfrost.dev
            https://www.nfrost.dev/groceries-list-app
            https://www.nfrost.dev/kvcc-department-directory
            https://www.nfrost.dev/kvcc-employee-directory
            https://www.nfrost.dev/kvcc-employee-portal
            https://www.nfrost.dev/kvcc-logos-branding-site
            https://www.nfrost.dev/kvcc-online-training
            https://www.nfrost.dev/kvcc-sign-in
            https://www.nfrost.dev/kvcc-staff-development
            https://www.nfrost.dev/kvcc-summit
          runs: 1